project_name: mctl
before:
  hooks:
    - go mod tidy

builds:
  - id: go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    ldflags:
      - -X "github.com/metal-toolbox/mctl/internal/version.AppVersion={{ .Version }}"
        -X "github.com/metal-toolbox/mctl/internal/version.GoVersion={{ .Env.GOVERSION }}"
        -X "github.com/metal-toolbox/mctl/internal/version.GitCommit={{ .Commit }}"
        -X "github.com/metal-toolbox/mctl/internal/version.GitBranch={{ .Branch }}"
        -X "github.com/metal-toolbox/mctl/internal/version.BuildDate={{ .Date }}"

archives:
  - id: go
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{ .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}64bit
      {{- else if eq .Arch "386" }}32bit
      {{- else if eq .Arch "arm" }}ARM
      {{- else if eq .Arch "arm64" }}ARM64
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - README.md

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

sboms:
  - artifacts: archive
  - id: source
    artifacts: source

signs:
  - cmd: cosign
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    args:
      - "sign-blob"
      - "--oidc-issuer=https://token.actions.githubusercontent.com"
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes" # required on cosign 2.0.0+
    artifacts: all
    output: true
